-- 실습 1-2
create table customer (
    cid varchar2(20) primary key,
    name varchar2(20) not null,
    hp char(13) UNIQUE,
    adress varchar2(200),
    rdate date
    );
 drop table customer;   
create table product (
    pno number(4) primary key,
    pname varchar2(30) not null,
    stock number DEFAULT 0 not null,
    price number,
    company varchar2(20) not null 
    );
   
    
create table orders (
    ord_no number generated by DEFAULT as IDENTITY primary key,
    ord_cid varchar2(20) not null,
    ord_pno number(4) not null,
    ord_cnt number not null,
    ord_date date DEFAULT sysdate not null
    );

-- 실습 1-3
insert into customer VALUES ('c101', '김유신', '101-1234-1001', '김해시 봉황동', '2022-01-01');
insert into customer VALUES ('c102', '김춘추', '101-1234-1002', '경주시 보문동', '2022-01-02');
insert into customer VALUES ('c103', '장보고', '101-1234-1003', '완도군 청산면', '2022-01-03');
insert into customer VALUES ('c104', '강감찬', '101-1234-1004', '서울시 마포구', '2022-01-04');
insert into customer VALUES ('c105', '이성계', null, null, '2022-01-05');
insert into customer VALUES ('c106', '정철', '101-1234-1006', '경기도 용인시', '2022-01-06');
insert into customer VALUES ('c107', '허준', 'null', 'null', '2022-01-07');
insert into customer VALUES ('c108', '이순신', '101-1234-1008', '서울시 영등포구', '2022-01-08');
insert into customer VALUES ('c109', '송상현', '101-1234-1009', '부산시 동래구', '2022-01-09');
insert into customer VALUES ('c110', '정약용', '101-1234-1010', '경기도 광주시', '2022-01-10');

insert into product VALUES (1, '새우깡', 5000, 1500, '농심');
insert into product VALUES (2, '초코파이', 2500, 2500, '오리온');
insert into product VALUES (3, '포카칩', 3600, 1700, '오리온');
insert into product VALUES (4, '양파링', 1250, 1800, '농심');
insert into product VALUES (5, '죠리퐁', 2200, null, '크라운');
insert into product VALUES (6, '마가렛트', 3500, 3500, '롯데');
insert into product VALUES (7, '뿌셔뿌셔', 1650, 1200, '오뚜기');

insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c102', 3, 2, '2022-07-01 13:15:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c101', 4, 1, '2022-07-01 14:16:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c108', 1, 1, '2022-07-01 17:15:11');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c109', 6, 5, '2022-07-02 13:36:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c102', 2, 1, '2022-07-03 09:15:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c101', 7, 3, '2022-07-03 07:15:37');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c110', 1, 2, '2022-07-03 16:55:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c104', 2, 4, '2022-07-04 21:09:34');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c102', 1, 3, '2022-07-04 13:54:10');
insert into orders(ord_cid, ord_pno, ord_cnt, ord_date) VALUES ('c107', 6, 1, '2022-07-05 14:12:21');

-- 실습 1-4
select * from customer;

-- 실습 1-5
select cid, name, hp from customer;

-- 실습 1-6
select * from product;

-- 실습 1-7
select company from product;

-- 실습 1-8
select DISTINCT company from product;

-- 실습 1-9
select pname, price from product;

-- 실습 1-10
select pname, price+500 as 조정단가 from product;

-- 실습 1-11
select pname, stock, price from product where company = '오리온';

-- 실습 1-12
select ord_pno, ord_cnt, ord_date from orders where ord_cid = 'c102';

-- 실습 1-13
select ord_pno, ord_cnt, ord_date from orders
where ord_cid = 'c102' and ord_cnt >= 2;

-- 실습 1-14
select * from product
where price BETWEEN 1000 and 2000;

-- 실습 1-15
select cid, name, hp, address from customer
where name like '김%';

-- 실습 1-16
select cid, name, hp, address from customer
where name like '__';

-- 실습 1-17
select * from customer where hp is null;

-- 실습 1-18
select * from customer where address is not null;

-- 실습 1-19
select * from customer
order by rdate desc;

-- 실습 1-20
select * from orders
where ord_cnt >= 3
order by ord_cnt desc, ord_pno asc;

-- 실습 1-21
select avg(price) from product;

-- 실습 1-22
select sum(stock) as "재고량 합계" from product
where company='농심';

-- 실습 1-23
select count(*) as 고객수 from customer;

-- 실습 1-24
select count(distinct company) as "제조업체 수" from product;

-- 실습 1-25
select ord_pno as "주문 상품번호", sum(ord_cnt) as "총 주문수량"
from orders
group by ord_pno;

-- 실습 1-26
select company as 제조업체, count(*) as 제품수, max(price) as 최고가
from product
GROUP by company;

-- 실습 1-27
select company as 제조업체, count(*) as 제품수, max(price) as 최고가
from product
GROUP by company
having count(*) >= 2;

-- 실습 1-28
select ord_pno, ord_cid, sum(ord_cnt) as "총 주문수량"
from orders
GROUP by ord_pno, ord_cid
order by ord_pno;

-- 실습 1-29
select ord_cid, pname from orders a join product p
on p.pno = a.ord_pno
where ord_cid = 'c102';

-- 실습 1-30
SELECT a.ord_cid, b.name, c.pname, a.ord_date
FROM orders a
JOIN customer b ON a.ord_cid = b.cid
JOIN product c ON a.ord_pno = c.pno
WHERE trunc(a.ord_date) = TO_DATE('2022-07-03', 'YYYY-MM-DD');


